In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df_full = pd.read_csv("survey.csv")
df = df_full[['How often do you attend office hours?', 'How often do you attend lectures for your classes?', 'How often do you ask questions in your lectures?', 'Do you work on or off campus?', 'How many extracurricular activities do you partake in? (Clubs/Fraternities, Teams, Sports, Jobs).', 'How many hours in a typical week do you work?']].copy()
df.head()

,How often do you attend office hours?,How often do you attend lectures for your classes?,How often do you ask questions in your lectures?,Do you work on or off campus?,"How many extracurricular activities do you partake in? (Clubs/Fraternities, Teams, Sports, Jobs).",How many hours in a typical week do you work?
0,2,5,2,On campus,1,20
1,1,5,2,Off Campus,2,20
2,2,5,4,NaN,2,0
3,3,4,2,Off Campus,1,10
4,1,5,1,NaN,0,0